
package gp8_traveltogether.vistas;

import gp8_traveltogether.entidades.Paquete;
import gp8_traveltogether.entidades.Turista;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;


public class vistaPresupuesto extends javax.swing.JInternalFrame {

    private Paquete paquete;
    
    public vistaPresupuesto(Paquete paquete) {
        this.paquete = paquete;
        initComponents();
        mostrarPresupuesto();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jbSiguiente = new javax.swing.JButton();
        jlIdaVuelta = new javax.swing.JLabel();
        jlFechas = new javax.swing.JLabel();
        jlGrupo = new javax.swing.JLabel();
        jlAdultos = new javax.swing.JLabel();
        jlMenores = new javax.swing.JLabel();
        jlPrecioAdulto = new javax.swing.JLabel();
        jlPrecioMenor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo.setText("Presupuesto paquete:");

        jbSiguiente.setText("Cerrar");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });

        jlIdaVuelta.setText("Paquete:");

        jlFechas.setText("Fechas:");

        jlGrupo.setText("Grupo: personas");

        jlAdultos.setText("Adultos:");

        jlMenores.setText("Menores:");

        jlPrecioAdulto.setText("Precio adulto:");

        jlPrecioMenor.setText("Precio menor:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSiguiente)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlGrupo)
                                .addGap(86, 86, 86)
                                .addComponent(jlAdultos)
                                .addGap(107, 107, 107)
                                .addComponent(jlMenores))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlIdaVuelta)
                                .addGap(234, 234, 234)
                                .addComponent(jlFechas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jlPrecioAdulto)
                        .addGap(139, 139, 139)
                        .addComponent(jlPrecioMenor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdaVuelta)
                    .addComponent(jlFechas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGrupo)
                    .addComponent(jlAdultos)
                    .addComponent(jlMenores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPrecioAdulto)
                    .addComponent(jlPrecioMenor))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jbSiguiente)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
           dispose();
    }//GEN-LAST:event_jbSiguienteActionPerformed
    
    private void mostrarPresupuesto(){
        jlTitulo.setText("Presupuesto paquete N°: "+paquete.getCodigoPaquete());
        jlIdaVuelta.setText(paquete.getBoleto().toString());
        DateTimeFormatter formatoNuestro = DateTimeFormatter.ofPattern("dd/MM/yy");
        jlFechas.setText("Fechas: "+ (paquete.getFechaInicio()).format(formatoNuestro) + " - " + (paquete.getFechaFin()).format(formatoNuestro));
        jlGrupo.setText("Grupo: "+paquete.getTuristas().size()+ " personas");
        
        int menores = 0;
        int adultos = 0;
        for (Turista turi:paquete.getTuristas()){
            if (turi.getEdad()<10){
                menores++;
            }else{
                adultos++;
            }
        }
        
        jlAdultos.setText("Adultos: "+adultos);
        jlMenores.setText("Menores: "+menores);
        jlPrecioAdulto.setText("Precio adulto: "+paquete.costoAdulto()+ " pesos");
        jlPrecioMenor.setText("Precio menor: "+paquete.costoMenor()+ " pesos");
        
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JLabel jlAdultos;
    private javax.swing.JLabel jlFechas;
    private javax.swing.JLabel jlGrupo;
    private javax.swing.JLabel jlIdaVuelta;
    private javax.swing.JLabel jlMenores;
    private javax.swing.JLabel jlPrecioAdulto;
    private javax.swing.JLabel jlPrecioMenor;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
