
package gp8_traveltogether.vistas;

import gp8_traveltogether.entidades.Paquete;
import gp8_traveltogether.entidades.Turista;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;


public class vistaPresupuesto extends javax.swing.JInternalFrame {

    private Paquete paquete;
    private DefaultTableModel detallePresupuesto = new DefaultTableModel();
    
    public vistaPresupuesto(Paquete paquete) {
        this.paquete = paquete;
        initComponents();
        armarTablaPresupuesto();
        mostrarPresupuesto();
        
        System.out.println(paquete);
        System.out.println(paquete.getTuristas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jbSiguiente = new javax.swing.JButton();
        jlIdaVuelta = new javax.swing.JLabel();
        jlGrupo = new javax.swing.JLabel();
        jlAdultos = new javax.swing.JLabel();
        jlMenores = new javax.swing.JLabel();
        jlPrecioPromedio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPresupuesto = new javax.swing.JTable();
        jlTotal = new javax.swing.JLabel();
        jlTemporada = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlAlojaNombre = new javax.swing.JLabel();
        jlTipoTransporte = new javax.swing.JLabel();
        jlPension = new javax.swing.JLabel();
        jlTraslado = new javax.swing.JLabel();

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo.setText("Presupuesto paquete:");

        jbSiguiente.setText("Cerrar");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });

        jlIdaVuelta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlIdaVuelta.setText("Paquete:");

        jlGrupo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlGrupo.setText("Grupo: personas");

        jlAdultos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlAdultos.setText("Adultos:");

        jlMenores.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlMenores.setText("Menores:");

        jlPrecioPromedio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlPrecioPromedio.setText("Precio promedio:");

        tablaPresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPresupuesto);

        jlTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTotal.setText("Total: $");

        jlTemporada.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlTemporada.setText("Temporada:");

        jlAlojaNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlAlojaNombre.setText("Alojamiento:");

        jlTipoTransporte.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlTipoTransporte.setText("Tipo de transporte:");

        jlPension.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlPension.setText("Pensión:");

        jlTraslado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlTraslado.setText("Traslados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jlTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSiguiente)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlGrupo)
                                            .addComponent(jlPrecioPromedio))
                                        .addGap(76, 76, 76)
                                        .addComponent(jlAdultos))
                                    .addComponent(jlIdaVuelta))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTemporada)
                                    .addComponent(jlMenores)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTipoTransporte)
                            .addComponent(jlAlojaNombre)
                            .addComponent(jlPension)
                            .addComponent(jlTraslado))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdaVuelta)
                    .addComponent(jlTemporada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGrupo)
                    .addComponent(jlAdultos)
                    .addComponent(jlMenores))
                .addGap(18, 18, 18)
                .addComponent(jlPrecioPromedio)
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAlojaNombre)
                .addGap(18, 18, 18)
                .addComponent(jlTipoTransporte)
                .addGap(13, 13, 13)
                .addComponent(jlPension)
                .addGap(18, 18, 18)
                .addComponent(jlTraslado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSiguiente)
                    .addComponent(jlTotal))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
           dispose();
    }//GEN-LAST:event_jbSiguienteActionPerformed
    
    private void mostrarPresupuesto(){
        jlTitulo.setText("Presupuesto paquete N°: "+paquete.getCodigoPaquete());
        DateTimeFormatter formatoNuestro = DateTimeFormatter.ofPattern("dd/MM/yy");
        jlIdaVuelta.setText(paquete.getBoleto().toString()+ " // "+"Fechas: "+ (paquete.getFechaInicio()).format(formatoNuestro) + " - " + (paquete.getFechaFin()).format(formatoNuestro));
        jlTemporada.setText("Viaje en temporada: " + paquete.getTemporada() + " - Duración: " + paquete.totalDias() + " días");
        jlGrupo.setText("Grupo: "+paquete.getTuristas().size()+ " personas");
        
        int menores = 0;
        int adultos = 0;
        for (Turista turi:paquete.getTuristas()){
            if (turi.getEdad()<10){
                menores++;
            }else{
                adultos++;
            }
        }
        
        jlAdultos.setText("Adultos: "+adultos);
        jlMenores.setText("Menores: "+menores);
        //jlPrecioPromedio;
        
        jlAlojaNombre.setText("Alojamiento: " + paquete.getEstadia().getTipoAlojam() + " " +paquete.getEstadia().getNombre());
        jlTipoTransporte.setText("Tipo de transporte: "+ paquete.getBoleto().getTipoViaje());
        jlPension.setText("Pensión: "+ paquete.getPension().getNombre());
        boolean traslado = paquete.isTraslado();
        String tieneTraslado = traslado ? "Si": "No";
        jlTraslado.setText("Traslados: "+tieneTraslado);
        

        llenarTablaPresupuesto();
        
        jlTotal.setText("Total $: "+ paquete.getMontoFinal());
        
        
    }
    
    public void llenarTablaPresupuesto(){
        detallePresupuesto.setRowCount(0);
        
        if (paquete.getTuristas() != null) {
        for (Turista turista : paquete.getTuristas()) {
            boolean esMenor = turista.getEdad() < 10;
            
            double alojamiento = paquete.getCostoAlojamiento(esMenor);
            double pasaje = paquete.getCostoPasaje(esMenor);
            double pension = paquete.getCostoPension(esMenor);
            double traslado = paquete.getCostoTraslado(esMenor, alojamiento + pension + pasaje);
            double costoTotal = alojamiento + pension + pasaje + traslado;
            double temporada = paquete.getRecargoTemporada(costoTotal);
            double plusCambio;
            
                if (esMenor){
                    plusCambio = (costoTotal+temporada)*0.1;
                }else{
                    plusCambio = (costoTotal+temporada)*0.1;
                }
            double totalPorPersona = costoTotal+temporada+plusCambio;

            
            Object[] fila = {
                turista.getNombre(),                // Nombre del turista
                alojamiento,                         // Costo de alojamiento
                pasaje,                             // Costo de pensión
                pension,                              // Costo de pasaje
                traslado,                            // Costo de traslado
                temporada,
                plusCambio,
                totalPorPersona,                           // Costo total (alojamiento + pensión + pasaje + traslado)
            };

            
            detallePresupuesto.addRow(fila);
        }
    }
}
    
   
    public void armarTablaPresupuesto(){
        detallePresupuesto.addColumn("Nombre");
        detallePresupuesto.addColumn("Alojamiento");
        detallePresupuesto.addColumn("Pasaje");
        detallePresupuesto.addColumn("Pension");
        detallePresupuesto.addColumn("Traslados");
        detallePresupuesto.addColumn("Plus temporada");
        detallePresupuesto.addColumn ("Plus por cambios");
        detallePresupuesto.addColumn("Total");
        
        tablaPresupuesto.setModel(detallePresupuesto);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JLabel jlAdultos;
    private javax.swing.JLabel jlAlojaNombre;
    private javax.swing.JLabel jlGrupo;
    private javax.swing.JLabel jlIdaVuelta;
    private javax.swing.JLabel jlMenores;
    private javax.swing.JLabel jlPension;
    private javax.swing.JLabel jlPrecioPromedio;
    private javax.swing.JLabel jlTemporada;
    private javax.swing.JLabel jlTipoTransporte;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JLabel jlTraslado;
    private javax.swing.JTable tablaPresupuesto;
    // End of variables declaration//GEN-END:variables
}
