/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gp8_traveltogether.vistas;

import gp8_traveltogether.entidades.Alojamiento;
import gp8_traveltogether.entidades.Ciudad;
import gp8_traveltogether.entidades.Paquete;
import gp8_traveltogether.entidades.Pasaje;
import gp8_traveltogether.entidades.Pension;
import gp8_traveltogether.entidades.Turista;
import gp8_traveltogether.persistencia.AlojamientoData;
import gp8_traveltogether.persistencia.CiudadData;
import gp8_traveltogether.persistencia.PaqueteData;
import gp8_traveltogether.persistencia.PasajeData;
import gp8_traveltogether.persistencia.PensionData;
import gp8_traveltogether.persistencia.TuristaData;
import static gp8_traveltogether.vistas.menu.escritorio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xiana
 */
public class vistaPaquete extends javax.swing.JInternalFrame {

    private ArrayList <Ciudad> ciudades = new ArrayList <>();
    private CiudadData ciudadData = new CiudadData();
    
    private PaqueteData paqueteData = new PaqueteData();
    private Paquete paqueteActual = null;
    
    private PasajeData pasajeData = new PasajeData();
    private Pasaje pasajeActual = new Pasaje();
    private ArrayList <Pasaje> pasajesPaquete = null;
    
    private TuristaData turiData = new TuristaData();
    private Turista turistaActual = null;
    private ArrayList <Turista> turistas = null;
    
    private AlojamientoData alojaData = new AlojamientoData();
    private Alojamiento alojamiento = null;
    private ArrayList <Alojamiento> alojamPorCiudad = null;
    
    private PensionData pensionData = new PensionData();
    private Pension pensionActual = null;
    private ArrayList<Pension> pensiones = new ArrayList<>();
    
    private DefaultTableModel modeloAlojam = new DefaultTableModel();
    private DefaultTableModel modeloPasaje = new DefaultTableModel();
    
    
    
    public vistaPaquete() {
        initComponents();
        
        ciudades = ciudadData.mostrarCiudades();
        pensiones = pensionData.mostrarPensiones();
        cargarOrigen();
        cargarDestino();
        cargarPension();
        armarTablaAlojam();
        armarTablaPasaje();
        
        jcDestino.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Ciudad ciudadSeleccionada = (Ciudad) jcDestino.getSelectedItem();
                if (ciudadSeleccionada != null) {
                    cargarAlojamPorDestino();
                }
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcOrigen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcDestino = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlojamiento = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePasaje = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jbCrear = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jrTraslado = new javax.swing.JRadioButton();
        jcPension = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jbGuardarPaquete = new javax.swing.JButton();
        jdIda = new com.toedter.calendar.JDateChooser();
        jdVuelta = new com.toedter.calendar.JDateChooser();
        jlTemporada = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtCodigoPaquete = new javax.swing.JTextField();
        jbEliminar = new javax.swing.JButton();
        jbBuscarPaquete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtEdadTuri = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jcTuristas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jbMostrarTuri = new javax.swing.JButton();
        jbLimpiarTuri = new javax.swing.JButton();
        jbGuardarTuri = new javax.swing.JButton();
        jtNombreTuri = new javax.swing.JTextField();
        jtDniTuri = new javax.swing.JTextField();
        jbActualizarTuri = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 982));
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 20)); // NOI18N
        jLabel1.setText("Paquete");

        jcOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcOrigenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel2.setText("Origen:");

        jcDestino.setToolTipText("");
        jcDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDestinoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel4.setText("Ida:");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel5.setText("Vuelta:");

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel12.setText("Alojamiento");

        tableAlojamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableAlojamiento);

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel13.setText("Pasajes");

        tablePasaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablePasaje);

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel15.setText("Destino:");

        jbCrear.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jbCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/crear_guardar_edit.png"))); // NOI18N
        jbCrear.setText("Crear");
        jbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel16.setText("Adicionales");

        jrTraslado.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jrTraslado.setText("Traslados");
        jrTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTrasladoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel3.setText("Pension:");

        jButton4.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mostrar_edit.png"))); // NOI18N
        jButton4.setText("Importe original");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbGuardarPaquete.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jbGuardarPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/crear_guardar_edit.png"))); // NOI18N
        jbGuardarPaquete.setText("Guardar paquete");
        jbGuardarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarPaqueteActionPerformed(evt);
            }
        });

        jlTemporada.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel6.setText("Codigo:");

        jbEliminar.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar_edit.png"))); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbBuscarPaquete.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jbBuscarPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lupa_edit.png"))); // NOI18N
        jbBuscarPaquete.setText("Buscar");
        jbBuscarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarPaqueteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrar-sesion.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/limpiar_edit.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel8.setText("DNI:");

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel9.setText("Nombre completo:");

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel7.setText("Cargar viajeros");

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel10.setText("Edad:");

        jButton2.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar_edit.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jLabel11.setText("Grupo:");

        jbMostrarTuri.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jbMostrarTuri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mostrar_edit.png"))); // NOI18N
        jbMostrarTuri.setText("Mostrar");
        jbMostrarTuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarTuriActionPerformed(evt);
            }
        });

        jbLimpiarTuri.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jbLimpiarTuri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/limpiar_edit.png"))); // NOI18N
        jbLimpiarTuri.setText("Limpiar");
        jbLimpiarTuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarTuriActionPerformed(evt);
            }
        });

        jbGuardarTuri.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jbGuardarTuri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salvar_edit.png"))); // NOI18N
        jbGuardarTuri.setText("Guardar");
        jbGuardarTuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarTuriActionPerformed(evt);
            }
        });

        jtNombreTuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreTuriActionPerformed(evt);
            }
        });

        jtDniTuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDniTuriActionPerformed(evt);
            }
        });

        jbActualizarTuri.setFont(new java.awt.Font("Lucida Sans", 1, 13)); // NOI18N
        jbActualizarTuri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/actualizar_turi_edit.png"))); // NOI18N
        jbActualizarTuri.setText("Actualizar");
        jbActualizarTuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarTuriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jtDniTuri, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jcTuristas, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jbMostrarTuri)
                .addGap(40, 40, 40)
                .addComponent(jButton2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jtNombreTuri, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtEdadTuri, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbGuardarTuri)
                .addGap(28, 28, 28)
                .addComponent(jbLimpiarTuri)
                .addGap(18, 18, 18)
                .addComponent(jbActualizarTuri))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jtDniTuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtNombreTuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jtEdadTuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGuardarTuri)
                    .addComponent(jbLimpiarTuri)
                    .addComponent(jbActualizarTuri))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jcTuristas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMostrarTuri)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(495, 495, 495)
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbGuardarPaquete)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jbEliminar)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jlTemporada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel13)
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jcOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdIda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jcDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jdVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCrear)
                            .addComponent(jbBuscarPaquete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16)
                        .addGap(83, 83, 83)
                        .addComponent(jrTraslado)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcPension, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(jtCodigoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscarPaquete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jbCrear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdIda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jlTemporada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel16)
                            .addComponent(jrTraslado)
                            .addComponent(jLabel3)
                            .addComponent(jcPension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jbGuardarPaquete)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jbEliminar)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcOrigenActionPerformed

    private void jtNombreTuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreTuriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreTuriActionPerformed

    private void jrTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTrasladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrTrasladoActionPerformed

    private void jbGuardarTuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarTuriActionPerformed
        // TODO add your handling code here:
        try{
            Integer dni=Integer.parseInt(jtDniTuri.getText());
            String nombre=jtNombreTuri.getText();
            Integer edad = Integer.parseInt(jtEdadTuri.getText());
          
            if(nombre.isEmpty()){
                JOptionPane.showMessageDialog(this, "No puede haber campos vacios");
                return;
            }
            
            if(turistaActual == null){
                turistaActual = new Turista (dni,nombre, edad);
                paqueteActual.agregarTurista(turistaActual);
 
                JOptionPane.showMessageDialog(this,"El turista se agregó al paquete.");
         
            }else {
                turistaActual.setDni(dni);
                turistaActual.setNombre(nombre);
                turistaActual.setEdad(edad);
                
                JOptionPane.showMessageDialog(this,"Turista actualizado");
            }
            
            DefaultComboBoxModel<Turista> model = new DefaultComboBoxModel<>(paqueteActual.getTuristas().toArray(new Turista[0]));
            jcTuristas.setModel(model); 
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,"Ingrese números válidos");
    }                                         
    }//GEN-LAST:event_jbGuardarTuriActionPerformed

    private void jcDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDestinoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcDestinoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mostrarPresupuestoOriginal();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearActionPerformed
        // TODO add your handling code here:
        try{
            if((jcOrigen.getSelectedItem() == null)|| (jcDestino.getSelectedItem() == null) || (jdIda.getDate()==null)|| (jdVuelta.getDate()==null)){
                JOptionPane.showMessageDialog(null, "No puede haber campos vacíos. Seleccione.");
                return;
            }
            
            Ciudad origen = (Ciudad) jcOrigen.getSelectedItem();
            Ciudad destino = (Ciudad) jcDestino.getSelectedItem();
            
            LocalDate fechaIda= jdIda.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaVuelta= jdVuelta.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            if (origen.getCodCiudad() == destino.getCodCiudad()){
                JOptionPane.showMessageDialog(this,"Las ciudades de origen y destino no pueden ser iguales.");
                return;
            }
            
            LocalDate hoy = LocalDate.now();
            
            if (fechaIda.isBefore(hoy) || fechaVuelta.isBefore(hoy) || fechaIda == fechaVuelta || fechaVuelta.isBefore(fechaIda)){
                JOptionPane.showMessageDialog(this,"Error. Verifique las fechas ingresadas.");
                return;
            }
            
            if(paqueteActual == null){
               paqueteActual = new Paquete(origen, destino, fechaIda, fechaVuelta);
               paqueteActual.setOrigen(origen);
               paqueteActual.setDestino(destino);
               paqueteActual.setFechaInicio(fechaIda);
               paqueteActual.setFechaFin(fechaVuelta);  
               jlTemporada.setText("Viaje en temporada: " + paqueteActual.getTemporada()+ " - Duración: "+ paqueteActual.totalDias()+ " días");
               
               cargarPasajes();
            }else{
                paqueteActual.setOrigen(origen);
                paqueteActual.setDestino(destino);
                paqueteActual.setFechaInicio(fechaIda);
                paqueteActual.setFechaFin(fechaVuelta);
                jlTemporada.setText("Viaje en temporada: " + paqueteActual.getTemporada() + " - Duración: " + paqueteActual.totalDias() + " días");
                JOptionPane.showMessageDialog(this, "Fechas y destinos actualizados.");
                
                cargarPasajes(); 
            }
        } catch (Exception e){
                JOptionPane.showMessageDialog(this,"Error al crear el paquete.");     
        }       
    }//GEN-LAST:event_jbCrearActionPerformed

    private void jtDniTuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDniTuriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDniTuriActionPerformed

    private void jbLimpiarTuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarTuriActionPerformed
        // TODO add your handling code here:
        jtDniTuri.setText("");
        jtNombreTuri.setText("");
        jtEdadTuri.setText("");
        turistaActual=null;
    }//GEN-LAST:event_jbLimpiarTuriActionPerformed

    private void jbGuardarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarPaqueteActionPerformed
        // TODO add your handling code here:
        if (paqueteActual != null){
            int filaAloj = tableAlojamiento.getSelectedRow();
            if(filaAloj !=-1){
                Ciudad citySeleccionada = (Ciudad)jcDestino.getSelectedItem();
                alojamPorCiudad = (ArrayList) alojaData.mostrarAlojPorCiudad(citySeleccionada.getCodCiudad());

                Alojamiento alojSelected = alojamPorCiudad.get(filaAloj);;
                paqueteActual.setEstadia(alojSelected);
            }else {
                JOptionPane.showMessageDialog(this, "Selecciona un alojamiento.");
                return;
            }
        }
        
        int filaPasaje = tablePasaje.getSelectedRow();
        if (filaPasaje  !=-1){
            Ciudad origen = (Ciudad) jcOrigen.getSelectedItem();
            Ciudad destino = (Ciudad) jcDestino.getSelectedItem();
        
            pasajesPaquete = (ArrayList) pasajeData.mostrarPasajes(origen, destino);
            
            Pasaje pasajeSelected = pasajesPaquete.get(filaPasaje);
            paqueteActual.setBoleto(pasajeSelected);
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona un pasaje.");
            return;
        }
        
        boolean traslado = jrTraslado.isSelected();
        paqueteActual.setTraslado(traslado);
        
        Pension pensionSelected = (Pension) jcPension.getSelectedItem();
        if (pensionSelected != null){
            paqueteActual.setPension(pensionSelected);
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona una pensión.");
            return;
        }
        
       
        paqueteActual.setEstado(true);

        
        
        if(paqueteData.existePaquete(paqueteActual.getCodigoPaquete())){
            int rta = JOptionPane.showConfirmDialog(this, "Modificar el paquete implica un recargo del 10% por pasajero. Confirma?", "Confirmar modificación y recargo",JOptionPane.OK_CANCEL_OPTION);
            if (rta ==0){
                double montoFinalRecargo = paqueteActual.calcularMontoFinalConRecargo();
                paqueteActual.setMontoFinal(montoFinalRecargo);
                paqueteData.modificarPaquete(paqueteActual);
                JOptionPane.showMessageDialog(this, "Paquete modificado.");
                mostrarPresupuestoModificacion();
            
            }else{
                JOptionPane.showMessageDialog(this, "Modificación cancelada.");
                dispose();
            }
        }else{
            double montoFinal = paqueteActual.calcularMontoFinal();
            paqueteActual.setMontoFinal(montoFinal);
            paqueteData.guardarPaquete(paqueteActual);
            JOptionPane.showMessageDialog(this, "Paquete guardado.");
            mostrarPresupuestoOriginal();
        } 
        
        if (paqueteActual.getTuristas()!=null && !paqueteActual.getTuristas().isEmpty()){
            for (Turista turista : paqueteActual.getTuristas()) {
                if (!turiData.existeTuristaEnPaquete(turista.getDni(), paqueteActual.getCodigoPaquete())) {
                    turista.setCodigoPaquete(paqueteActual.getCodigoPaquete()); 
                    turiData.agregarTurista(turista);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Cargue uno o más turistas.");
            return;
        }

    }//GEN-LAST:event_jbGuardarPaqueteActionPerformed
    
    private void mostrarPresupuestoOriginal(){
        vistaPresupuesto2 vistaPresuO = new vistaPresupuesto2(paqueteActual);
        escritorio.add(vistaPresuO);
        vistaPresuO.setVisible(true);
    }
    
    private void mostrarPresupuestoModificacion(){
        vistaPresupuesto vistaPresuM = new vistaPresupuesto(paqueteActual);
        escritorio.add(vistaPresuM);
        vistaPresuM.setVisible(true);  
}
    private void jbBuscarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarPaqueteActionPerformed
        // TODO add your handling code here:
        try{
            if (jtCodigoPaquete.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un código.");
                return;
            }
            
            Integer codigoPaquete = Integer.parseInt(jtCodigoPaquete.getText());
            paqueteActual = paqueteData.buscarPaquete(codigoPaquete);
            
            if(paqueteActual !=null){
                Ciudad origen = paqueteActual.getOrigen();
                for (int i = 0; i < jcOrigen.getItemCount(); i++) {
                        Ciudad ciudad = (Ciudad) jcOrigen.getItemAt(i);
                        if (ciudad.getCodCiudad() == origen.getCodCiudad()) {
                            jcOrigen.setSelectedIndex(i);
                            break;
                        }
                }
                
                Ciudad destino = paqueteActual.getDestino();
                for (int i = 0; i < jcDestino.getItemCount(); i++) {
                        Ciudad ciudad = (Ciudad) jcDestino.getItemAt(i);
                        if (ciudad.getCodCiudad() == destino.getCodCiudad()) {
                            jcDestino.setSelectedIndex(i);
                            break;
                        }
                }
                
                LocalDate ida = paqueteActual.getFechaInicio();
                java.util.Date fIda=java.util.Date.from(ida.atStartOfDay(ZoneId.systemDefault()).toInstant());
                jdIda.setDate(fIda);
                
                LocalDate vuelta = paqueteActual.getFechaFin();
                java.util.Date fVuelta=java.util.Date.from(vuelta.atStartOfDay(ZoneId.systemDefault()).toInstant());
                jdVuelta.setDate(fVuelta);
                
                jlTemporada.setText("Viaje en temporada: " + paqueteActual.getTemporada()+ " - Duración: "+ paqueteActual.totalDias()+ " días");
                
                paqueteActual.setTuristas(paqueteData.mostrarTuristasPorPaquete(codigoPaquete));
                    for (Turista turista : paqueteActual.getTuristas()){
                        jcTuristas.addItem(turista); 
                    }
                    
                cargarPasajes();
                
                jrTraslado.setSelected(paqueteActual.isEstado());
                Pension pensionActual = paqueteActual.getPension();
                for (int i = 0; i < jcPension.getItemCount(); i++) {
                    Pension pension = (Pension) jcPension.getItemAt(i);
                    if (pension.getCodAdicional() == pensionActual.getCodAdicional()) {
                        jcPension.setSelectedIndex(i);
                        break;
                    }
                } 
            }
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Número no válido.");
        }
    }//GEN-LAST:event_jbBuscarPaqueteActionPerformed

    private void jbActualizarTuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarTuriActionPerformed
        // TODO add your handling code here:
        turistaActual = (Turista) jcTuristas.getSelectedItem();
        Integer dni=Integer.parseInt(jtDniTuri.getText());
        String nombre=jtNombreTuri.getText();
        Integer edad = Integer.parseInt(jtEdadTuri.getText());
        if(turistaActual !=null){
            turistaActual.setDni(dni);
            turistaActual.setNombre(nombre);
            turistaActual.setEdad(edad);
            turiData.modificarTurista(turistaActual);
            JOptionPane.showMessageDialog(this,"Turista actualizado");
        } else {
            JOptionPane.showMessageDialog(this,"No se pudo actualizar.");
        }        
    }//GEN-LAST:event_jbActualizarTuriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Turista turiEliminar = (Turista) jcTuristas.getSelectedItem();
        
        if (turiEliminar !=null){
            paqueteActual.eliminarTurista(turiEliminar);
            jcTuristas.removeItem(turiEliminar);
            
        } else{
            JOptionPane.showMessageDialog(this,"Selecciona el turista a eliminar.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbMostrarTuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarTuriActionPerformed
        // TODO add your handling code here:
        Turista turiMostrar = (Turista) jcTuristas.getSelectedItem();
        if(turiMostrar != null){
            jtDniTuri.setText(String.valueOf(turiMostrar.getDni()));
            jtNombreTuri.setText(turiMostrar.getNombre());
            jtEdadTuri.setText(String.valueOf(turiMostrar.getEdad()));
        }
        
    }//GEN-LAST:event_jbMostrarTuriActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        paqueteActual = null;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        LocalDate ida = paqueteActual.getFechaInicio();
        LocalDate hoy = LocalDate.now();
        long cantDias = ChronoUnit.DAYS.between(hoy, ida);
        if (paqueteActual != null && cantDias>30 ){
            paqueteData.bajaLogicaPaquete(paqueteActual.getCodigoPaquete());
            paqueteActual = null;
            limpiarCampos();
           
        }else{
            JOptionPane.showMessageDialog(this, "Restan menos de 30 días para el viaje. No se puede eliminar el paquete.");
        }
    }//GEN-LAST:event_jbEliminarActionPerformed
    
    private void cargarOrigen(){
        jcOrigen.removeAllItems();
        jcOrigen.addItem(new Ciudad(0, "Seleccione", false));
        for (Ciudad c: ciudades){
            jcOrigen.addItem(c);
        }
    }
    
    public void cargarDestino(){
        jcDestino.removeAllItems();
        jcDestino.addItem(new Ciudad(0, "Seleccione", false));
        for (Ciudad c: ciudades){
            jcDestino.addItem(c);
        }  
    }
    
    public void cargarPension(){
        jcPension.removeAllItems();
        jcPension.addItem(new Pension (0, "Seleccione"));
        for (Pension p: pensiones){
            jcPension.addItem(p);
        }
    }
    
    private void actualizarCBTuristas() {
        jcTuristas.removeAllItems();
        for (Turista turista : paqueteActual.getTuristas()){
            jcTuristas.addItem(turista); 
        }
    }
    
    private void armarTablaAlojam(){
        modeloAlojam.addColumn("Nombre");
        modeloAlojam.addColumn("Tipo");
        modeloAlojam.addColumn("Capacidad");
        modeloAlojam.addColumn("Precio por noche");
        
        tableAlojamiento.setModel(modeloAlojam);
    }
    
    private void armarTablaPasaje(){
        modeloPasaje.addColumn("Medio de transporte");
        modeloPasaje.addColumn("Precio por persona");
        
        tablePasaje.setModel(modeloPasaje);
    }
    
    public void cargarAlojamPorDestino(){
        modeloAlojam.setRowCount(0);
        Ciudad citySeleccionada = (Ciudad)jcDestino.getSelectedItem();

        alojamPorCiudad = (ArrayList) alojaData.mostrarAlojPorCiudad(citySeleccionada.getCodCiudad());
        
        if (alojamPorCiudad == null || alojamPorCiudad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay alojamientos en el destino seleccionado.");
            return;
        }

        for (Alojamiento aloja : alojamPorCiudad) {
            modeloAlojam.addRow(new Object[] {
                aloja.getNombre(),
                aloja.getTipoAlojam(),
                aloja.getCapacidad(),
                aloja.getPrecioNoche() });
        }
        
    }
    
    public void cargarPasajes(){
        modeloPasaje.setRowCount(0);
        Ciudad origen = (Ciudad) jcOrigen.getSelectedItem();
        Ciudad destino = (Ciudad) jcDestino.getSelectedItem();
        
        ArrayList <Pasaje> pasajesPaquete = (ArrayList) pasajeData.mostrarPasajes(origen, destino);
        
        if (pasajesPaquete == null || pasajesPaquete.isEmpty()){
            JOptionPane.showMessageDialog(null, "No hay pasajes para el viaje seleccionado.");
            return;
        }
        
        for (Pasaje pasaje:pasajesPaquete){
            modeloPasaje.addRow(new Object[] {
                pasaje.getTipoViaje(),
                pasaje.getPrecioPasaje()});
        }
    }
    
    private void limpiarCampos(){
        jtCodigoPaquete.setText("");
        jcOrigen.setSelectedIndex(0);
        jcDestino.setSelectedIndex(0);
        jdIda.setDate(null);
        jdVuelta.setDate(null);
        jtDniTuri.setText("");
        jtNombreTuri.setText("");
        jtEdadTuri.setText("");
        jcTuristas.setSelectedItem(0);
        modeloAlojam.setRowCount(0);
        modeloPasaje.setRowCount(0);
        jrTraslado.setSelected(false);
        jcPension.setSelectedIndex(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbActualizarTuri;
    private javax.swing.JButton jbBuscarPaquete;
    private javax.swing.JButton jbCrear;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardarPaquete;
    private javax.swing.JButton jbGuardarTuri;
    private javax.swing.JButton jbLimpiarTuri;
    private javax.swing.JButton jbMostrarTuri;
    private javax.swing.JComboBox<Ciudad> jcDestino;
    private javax.swing.JComboBox<Ciudad> jcOrigen;
    private javax.swing.JComboBox<Pension> jcPension;
    private javax.swing.JComboBox<Turista> jcTuristas;
    private com.toedter.calendar.JDateChooser jdIda;
    private com.toedter.calendar.JDateChooser jdVuelta;
    private javax.swing.JLabel jlTemporada;
    private javax.swing.JRadioButton jrTraslado;
    private javax.swing.JTextField jtCodigoPaquete;
    private javax.swing.JTextField jtDniTuri;
    private javax.swing.JTextField jtEdadTuri;
    private javax.swing.JTextField jtNombreTuri;
    private javax.swing.JTable tableAlojamiento;
    private javax.swing.JTable tablePasaje;
    // End of variables declaration//GEN-END:variables
}
