/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gp8_traveltogether.vistas;

import gp8_traveltogether.entidades.Pension;
import gp8_traveltogether.persistencia.PensionData;
import javax.swing.JOptionPane;

/**
 *
 * @author xiana
 */
public class vistaPension extends javax.swing.JInternalFrame {
    PensionData pensionData = new PensionData();
    Pension pensionActual = null;
    

    
    public vistaPension() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jtCodPension = new javax.swing.JTextField();
        jtNombrePension = new javax.swing.JTextField();
        jtPorcentaje = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));
        getContentPane().add(jtCodPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 80, -1));
        getContentPane().add(jtNombrePension, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 160, -1));
        getContentPane().add(jtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 160, -1));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        bg.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pension600.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        if (pensionActual != null){
            pensionData.eliminarPension(pensionActual.getCodAdicional());
            pensionActual = null;
            limpiarCampos();
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        pensionActual = null;
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        try{
            String nombre = jtNombrePension.getText();
            String porcentaje = jtPorcentaje.getText();
            
            if(nombre.isEmpty()|| porcentaje.isEmpty()){
                JOptionPane.showMessageDialog(this, "Completa todos los campos.");
                return;
            }
            
            Double porcentaje2 = Double.parseDouble(porcentaje);
            
            if(pensionActual == null){
                pensionActual = new Pension (nombre, porcentaje2);
                pensionData.crearPension(pensionActual);
                JOptionPane.showMessageDialog(this,"Pensión creada.");
                limpiarCampos();
                pensionActual = null;
            }else{
                pensionActual.setNombre(nombre);
                pensionActual.setPorcentaje(porcentaje2);
                pensionData.modificarPension(pensionActual);
                JOptionPane.showMessageDialog(this,"Modificación exitosa.");
                limpiarCampos();
                pensionActual = null;
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Ingresa un porcentaje valido.");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        try{
            Integer cod = Integer.parseInt(jtCodPension.getText());
            pensionActual = pensionData.buscarPensionPorCod(cod);
            
            if (pensionActual !=null){
                jtNombrePension.setText(pensionActual.getNombre());
                jtPorcentaje.setText(String.valueOf(pensionActual.getPorcentaje()));
            } else{
                JOptionPane.showMessageDialog (null,"No existe una Pension con ese código");
            }
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog (null,"Ingresa un çódigo válido");
            
        }  
    }//GEN-LAST:event_jbBuscarActionPerformed
    

    private void limpiarCampos(){
        jtCodPension.setText("");
        jtNombrePension.setText("");
        jtPorcentaje.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtCodPension;
    private javax.swing.JTextField jtNombrePension;
    private javax.swing.JTextField jtPorcentaje;
    // End of variables declaration//GEN-END:variables
}
