/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gp8_traveltogether.vistas;

import gp8_traveltogether.entidades.Paquete;
import gp8_traveltogether.entidades.Turista;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xiana
 */
public class vistaPresupuesto2 extends javax.swing.JInternalFrame {

    private Paquete paquete;
    private DefaultTableModel detallePresupuesto = new DefaultTableModel();
    
    public vistaPresupuesto2(Paquete paquete) {
        initComponents();
        this.paquete = paquete;
        initComponents();
        armarTablaPresupuesto();
        mostrarPresupuestoModificacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jlIdaVuelta = new javax.swing.JLabel();
        jlTemporada = new javax.swing.JLabel();
        jlGrupo = new javax.swing.JLabel();
        jlPrecioPromedio = new javax.swing.JLabel();
        jlAlojaNombre = new javax.swing.JLabel();
        jlTipoTransporte = new javax.swing.JLabel();
        jlPension = new javax.swing.JLabel();
        jlAdultos = new javax.swing.JLabel();
        jlMenores = new javax.swing.JLabel();
        jlTraslado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPresupuesto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo.setText("Presupuesto paquete:");

        jlTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTotal.setText("Total: $");

        jlIdaVuelta.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlIdaVuelta.setText("Paquete:");

        jlTemporada.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlTemporada.setText("Temporada:");

        jlGrupo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlGrupo.setText("Grupo: personas");

        jlPrecioPromedio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlPrecioPromedio.setText("Precio promedio por persona:");

        jlAlojaNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlAlojaNombre.setText("Alojamiento:");

        jlTipoTransporte.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlTipoTransporte.setText("Tipo de Transporte:");

        jlPension.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlPension.setText("Pension:");

        jlAdultos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlAdultos.setText("Adultos:");

        jlMenores.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlMenores.setText("Menores:");

        jlTraslado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlTraslado.setText("Traslados:");

        tablaPresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPresupuesto);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTipoTransporte)
                    .addComponent(jlAlojaNombre)
                    .addComponent(jlTraslado)
                    .addComponent(jlPension)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTotal)
                .addGap(348, 348, 348)
                .addComponent(jButton1)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlGrupo)
                        .addGap(204, 204, 204)
                        .addComponent(jlAdultos)
                        .addGap(121, 121, 121)
                        .addComponent(jlMenores))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlIdaVuelta)
                        .addGap(130, 130, 130)
                        .addComponent(jlTemporada))
                    .addComponent(jlPrecioPromedio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdaVuelta)
                    .addComponent(jlTemporada))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGrupo)
                    .addComponent(jlAdultos)
                    .addComponent(jlMenores))
                .addGap(29, 29, 29)
                .addComponent(jlPrecioPromedio)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAlojaNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jlTipoTransporte)
                        .addGap(18, 18, 18)
                        .addComponent(jlPension)
                        .addGap(18, 18, 18)
                        .addComponent(jlTraslado)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jlTotal)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarPresupuestoModificacion(){
        jlTitulo.setText("Presupuesto paquete N°: "+paquete.getCodigoPaquete());
        DateTimeFormatter formatoNuestro = DateTimeFormatter.ofPattern("dd/MM/yy");
        jlIdaVuelta.setText(paquete.getBoleto().toString()+ " // "+"Fechas: "+ (paquete.getFechaInicio()).format(formatoNuestro) + " - " + (paquete.getFechaFin()).format(formatoNuestro));
        jlTemporada.setText("Viaje en temporada: " + paquete.getTemporada() + " - Duración: " + paquete.totalDias() + " días");
        jlGrupo.setText("Grupo: "+paquete.getTuristas().size()+ " personas");
        
        int menores = 0;
        int adultos = 0;
        for (Turista turi:paquete.getTuristas()){
            if (turi.getEdad()<10){
                menores++;
            }else{
                adultos++;
            }
        }
        
        jlAdultos.setText("Adultos: "+adultos);
        jlMenores.setText("Menores: "+menores);
        double promedio = paquete.calcularMontoFinal()/(menores+adultos);
        jlPrecioPromedio.setText("Precio promedio por persona: "+ promedio);
        
        jlAlojaNombre.setText("Alojamiento: " + paquete.getEstadia().getTipoAlojam() + " " +paquete.getEstadia().getNombre());
        jlTipoTransporte.setText("Tipo de transporte: "+ paquete.getBoleto().getTipoViaje());
        jlPension.setText("Pensión: "+ paquete.getPension().getNombre());
        boolean traslado = paquete.isTraslado();
        String tieneTraslado = traslado ? "Si": "No";
        jlTraslado.setText("Traslados: "+tieneTraslado);

        llenarTablaPresupuesto();
 
    }
    
    public void llenarTablaPresupuesto(){
        detallePresupuesto.setRowCount(0);
        
        if (paquete.getTuristas() != null) {
        for (Turista turista : paquete.getTuristas()) {
            boolean esMenor = turista.getEdad() < 10;
            
            double alojamiento = paquete.getCostoAlojamiento(esMenor);
            double pasaje = paquete.getCostoPasaje(esMenor);
            double pension = paquete.getCostoPension(esMenor);
            double traslado = paquete.getCostoTraslado(esMenor, alojamiento + pension + pasaje);
            double costoTotal = alojamiento + pension + pasaje + traslado;
            double temporada = paquete.getRecargoTemporada(costoTotal);
            double totalPorPersona = costoTotal+temporada;

            
            Object[] fila = {
                turista.getNombre(),                
                alojamiento,                         
                pasaje,                             
                pension,                              
                traslado,                          
                temporada,
                totalPorPersona,                          
            };

            
            detallePresupuesto.addRow(fila);
            jlTotal.setText("Total $: "+ paquete.calcularMontoFinal());
        }
    }
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void armarTablaPresupuesto(){
        detallePresupuesto.addColumn("Nombre");
        detallePresupuesto.addColumn("Alojamiento");
        detallePresupuesto.addColumn("Pasaje");
        detallePresupuesto.addColumn("Pension");
        detallePresupuesto.addColumn("Traslados");
        detallePresupuesto.addColumn("Plus temporada");
        detallePresupuesto.addColumn("Total");
        
        tablaPresupuesto.setModel(detallePresupuesto);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlAdultos;
    private javax.swing.JLabel jlAlojaNombre;
    private javax.swing.JLabel jlGrupo;
    private javax.swing.JLabel jlIdaVuelta;
    private javax.swing.JLabel jlMenores;
    private javax.swing.JLabel jlPension;
    private javax.swing.JLabel jlPrecioPromedio;
    private javax.swing.JLabel jlTemporada;
    private javax.swing.JLabel jlTipoTransporte;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JLabel jlTraslado;
    private javax.swing.JTable tablaPresupuesto;
    // End of variables declaration//GEN-END:variables
}
